name: Deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Config vcpkg
      run: |
        vcpkg integrate install
        
    - name: Build the solution
      run: |
        msbuild -p:Configuration=Release -p:Platform=x86 -restore -m
        
    - name: Delete unnecessary files
      run: |
        cd Release
        del *.exp -Force
        del *.lib -Force
        del *.pdb -Force
        del *.exe.config -Force
        del de -Recurse -Force
        cd ..
        
    - name: List built files
      run: |
        cd Release
        ls
        cd ..
        
    - name: Create artifact
      uses: actions/upload-artifact@v3
      with:
        name: Release build
        path: Release
